### ISSUE TITLE
Are snippets ready for refinery 2.1?

### ISSUE THREAD

**Issue by anitagraham** [keram/refinerycms-snippets#19]
I tried using snippets in my refinerycms 2.1 and got the following error:

`/Users/anita/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in`require': no such file to load -- refinerycms-base (LoadError)
        from /Users/anita/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in `block in require'
        from /Users/anita/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:236:in`load_dependency'
        from /Users/anita/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in `require'
        from /Users/anita/.rvm/gems/ruby-1.9.2-p290/gems/refinerycms-snippets-0.5/lib/refinerycms-snippets.rb:1:in`<top (required)>'`

Is there something simple I can do to move past this?

**Comment by MadWagon** [comment]
I am getting the same error, any idea for a fix ?

**Comment by anitagraham** [comment]
I went with refinerycms-copywriting which does much the same job.
gem 'refinerycms-copywriting', :branch => 'rails-3-1'

**Comment by anitagraham** [comment]
I changed over to refinerycms-copywriting which does work for refinery 2

gem 'refinerycms-copywriting', :branch => 'rails-3-1'

On 3/04/12 6:34 PM, "MadWagon"
<reply+i-3487902-a26446c3a5de8dfa1432423ce92838d1f1587806-397118@reply.githu
b.com> wrote:

> I am getting the same error, any idea for a fix ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/keram/refinerycms-snippets/issues/19#issuecomment-4898386

-- Anita Graham
anita@joli.com.au
