### ISSUE TITLE
Add new page breaks with snippets

### ISSUE THREAD

**Issue by sporkd** [keram/refinerycms-snippets#3]
Thanks for making this add-on to address what I see as the biggest missing feature in Refinery!!!

Everything worked fine except it breaks when three are already snippets in the database and you try and add a new page. This is because the snippets_field partial tries to use @page.id before the page has been saved to the database.  My quick fix was to override the admin/pages/tabs/snippets partial like so:

```
  <div class="wym_skin_refinery page_part" id="page_snippet_picker">
    <% if @page.new_record? %>
      <h2>Please save this page before you can add any snippets</h2>
    <% else %>
      <%= render :partial => '/admin/pages/tabs/snippets_content', :locals => {:f => f} %>
    <% end %>
  </div>
```

Works for now, but I'm guessing you'll want to do something more user friendly.  Perhaps with Rails nested_attributes or the like.

peter

**Comment by keram** [comment]
thank you for reporting!
For now I use your patch  and I start learn more about nested attributes ;-)
